AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-075d39ebbca89ed55
      InstanceType: t2.micro
      SubnetId: subnet-064cc1c38ece97bd0 
      UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            systemctl enable httpd.service
            systemctl start httpd.service
    #Add security group for the Webserver Instance to allow HTTP and SSH access
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: WebSRVR
  #Assign Public IP to EC2 Instance
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebServer
      Domain: vpc        
Outputs:
  EC2InstanceEIP:
    Description: EC2 instance public IP address
    Value: !Ref EIP